### ISSUE TITLE
empty response

### ISSUE THREAD

**Issue by chenziru** [brumik/obsidian-ollama-chat#5]
1. ollama running on localhost:11434
2. I have installed llama2 model 
3. I have run the codes following the "Manual run with python3" part (https://github.com/brumik/ollama-obsidian-indexer?tab=readme-ov-file)

however, no matter what questions I asked,  it return "Empty response"

<img width="555" alt="image-20240126143842528" src="https://github.com/brumik/obsidian-ollama-chat/assets/21326670/941af2ab-e849-4285-9bbc-9c662cdd6f35">

I am looking forward to your response.

**Comment by brumik** [comment]
Hello there, can you please check if then python indexer indexed your documents correctly? You can check in the directory wher it is running the `./storage` folder. You should be able to find in the document store pieces of your notes all around. If this is missing and empty context is passed to the LLM which can cause empty response. Also the default template is set up for Mistral model, though I am not sure if this could be a huge issue.

**Comment by chenziru** [comment]
Thank you for your response.
Here are files in my `storage` folder.
![Snipaste_2024-01-29_14-11-02](https://github.com/brumik/obsidian-ollama-chat/assets/21326670/33249a9c-340d-4b70-a3ca-b5158f1a92ca)

It seems they are empty.
```shell
cat default__vector_store.json 

{"embedding_dict": {}, "text_id_to_ref_doc_id": {}, "metadata_dict": {}}**%**                                  

% cat graph_store.json 

{"graph_dict": {}}**%**                                                                                        
% cat index_store.json 

{"index_store/data": {"52e05fd8-de0c-4672-9a89-3247f8bd07ee": {"__type__": "vector_store", "__data__": "{\"index_id\": \"52e05fd8-de0c-4672-9a89-3247f8bd07ee\", \"summary\": null, \"nodes_dict\": {}, \"doc_id_dict\": {}, \"embeddings_dict\": {}}"}}}**%**                                                                       
% cat docstore.json 

{}**%**                                                                                                        
% cat image__vector_store.json 

{"embedding_dict": {}, "text_id_to_ref_doc_id": {}, "metadata_dict": {}}**%**
```

And I set `NOTES_BASE_PATH="/Users/ziruchen/chenziru/work"` in the `.env` file. This is the path where I store my Obsidian markdown files. I don't know if I set it right.

**Comment by brumik** [comment]
Thank you, well it looks like your dictionary is empty and this will be the issue. When you are opening obsidian do you get any error messages in the notifications? As far as I can see the problem will be the indexing itself. Either the path is not available for the python app (or permissions are not allowing reading the files) or something else (but no idea what). 

(sorry to come back so late, it is hectic lately)

**Comment by chillja** [comment]
Not sure if that's the issue here, but I ran into the same error message. First issue was, that when Obsidian and the plugin already were already running and I then point it to a freshly started backend server it does not start an indexing and therefore the index is empty. It then happened again, when I after the first indexing changed the storage folder in the `.env` without restarting obsidian and therefore without a reindexing request from the plugin. Either way: Restarting Obsidian to force a reindexing helped.

**Comment by brumik** [comment]
Unfortunatelly the indexing is triggered by obsidian part of the plugin so changing locations can mess it up. In this cases I would also add that deleting the `storage` folder may be needed to avoid old data in the document store (and potentially leak information)

**Comment by chenziru** [comment]
> Thank you, well it looks like your dictionary is empty and this will be the issue. When you are opening obsidian do you get any error messages in the notifications? As far as I can see the problem will be the indexing itself. Either the path is not available for the python app (or permissions are not allowing reading the files) or something else (but no idea what).
> 
> (sorry to come back so late, it is hectic lately)

No, I had not got  error messege.

**Comment by chenziru** [comment]
> Not sure if that's the issue here, but I ran into the same error message. First issue was, that when Obsidian and the plugin already were already running and I then point it to a freshly started backend server it does not start an indexing and therefore the index is empty. It then happened again, when I after the first indexing changed the storage folder in the `.env` without restarting obsidian and therefore without a reindexing request from the plugin. Either way: Restarting Obsidian to force a reindexing helped.

Thank you.

I tried this:
1. open ollama
2. open obisidian
3. index
4. try Ollama AI chat
I got "Empty Response" without error messege.

And then I tried this:
1. open ollama
2. index
3. open obisidian
4. try Ollama AI chat
and I got an error messege.
![image](https://github.com/brumik/obsidian-ollama-chat/assets/21326670/0d1bafe2-1290-479c-887d-dba2a9144848)
when I exit index program I got another error messege:
![image](https://github.com/brumik/obsidian-ollama-chat/assets/21326670/dfcec15f-935c-4647-920b-d4380d04e140)

**Comment by brumik** [comment]
Did you see this 500 error in the Python app? There should be more information what broke down than in the notification.

**Comment by chenziru** [comment]
> Did you see this 500 error in the Python app? There should be more information what broke down than in the notification.

Yes, here are the error messeges.
```shell
Traceback (most recent call last):
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/ziruchen/chenziru/source_code/ollama-obsidian-indexer/server.py", line 45, in index
    response = query(user_query)
  File "/Users/ziruchen/chenziru/source_code/ollama-obsidian-indexer/llm.py", line 148, in query
    response = query_engine.query(query)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/core/base_query_engine.py", line 30, in query
    return self._query(str_or_query_bundle)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/query_engine/retriever_query_engine.py", line 171, in _query
    response = self._response_synthesizer.synthesize(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/response_synthesizers/base.py", line 146, in synthesize
    response_str = self.get_response(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/response_synthesizers/compact_and_refine.py", line 38, in get_response
    return super().get_response(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/response_synthesizers/refine.py", line 146, in get_response
    response = self._give_response_single(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/response_synthesizers/refine.py", line 202, in _give_response_single
    program(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/response_synthesizers/refine.py", line 64, in __call__
    answer = self._llm.predict(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/llms/llm.py", line 220, in predict
    chat_response = self.chat(messages)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/llms/base.py", line 97, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/llama_index/llms/ollama.py", line 102, in chat
    response = client.post(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1146, in post
    return self.request(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ziruchen/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
```

**Comment by brumik** [comment]
This looks really similar to the other reported error: https://github.com/brumik/ollama-obsidian-indexer/issues/6

I will close this in favor of that one and we will see if we can solve it.

Are you also using Mac?

**Comment by chenziru** [comment]
> This looks really similar to the other reported error: [brumik/ollama-obsidian-indexer#6](https://github.com/brumik/ollama-obsidian-indexer/issues/6)
> 
> I will close this in favor of that one and we will see if we can solve it.
> 
> Are you also using Mac?

Yes, I am using Mac.
Thank you!
